FROM node:19 AS build-step

WORKDIR /usr/src/app

COPY ./package.json .

RUN ["npm", "install"]

COPY . .

RUN ["npm", "run", "build"]

FROM nginx

COPY --from=build-step /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
